INSERT INTO tasks VALUES (DEFAULT, 'TEST TASK', 'TASK_IN_PROGRESS');
INSERT INTO tasks VALUES (DEFAULT, 'TEST TASK', 'TASK_IN_PROGRESS');
INSERT INTO tasks VALUES (DEFAULT, 'TEST TASK', 'TASK_IN_PROGRESS');
